# Generated by Django 3.2.4 on 2021-06-23 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDesignation',
            fields=[
                ('des_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_designation', models.CharField(max_length=50)),
                ('emp_salary', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_email', models.EmailField(max_length=50)),
                ('emp_phonenumber', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_profession', models.CharField(max_length=50)),
                ('emp_designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profession', to='myapp.employeedesignation')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_father_name', models.CharField(max_length=50)),
                ('emp_mother_name', models.CharField(max_length=50)),
                ('emp_father_occupation', models.CharField(max_length=50)),
                ('emp_mother_occupation', models.CharField(max_length=50)),
                ('emp_father_mobile_number', models.CharField(max_length=12)),
                ('emp_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_details', to='myapp.employeemodel')),
            ],
        ),
        migrations.AddField(
            model_name='employeedesignation',
            name='emp_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designation', to='myapp.employeemodel'),
        ),
        migrations.CreateModel(
            name='EmployeeAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_street_name', models.CharField(max_length=100)),
                ('emp_city_name', models.CharField(max_length=100)),
                ('emp_state_name', models.CharField(max_length=75)),
                ('emp_Zip_number', models.CharField(max_length=10)),
                ('emp_country_name', models.CharField(max_length=50)),
                ('emp_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='myapp.employeemodel')),
            ],
        ),
    ]
